<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutoClickerTest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
  </ItemGroup>

</Project>
